GET http://localhost:3001/api/blogs

### 

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "test title",
    "author": "John Doe",
    "url": "https://google.com",
    "likes": 7
}

### 

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "game of thrones",
    "author": "George RR Martin",
    "url": "https://grrmartin.com",
    "likes": 51
}

###

DELETE http://localhost:3001/api/blogs/66a65c317b13e7648695f3a6

###

PUT http://localhost:3001/api/blogs/66a521dbe378a9c24d28a930
Content-Type: application/json

{
    "likes": 17,
    "title": "harry potter"
}

### 

GET http://localhost:3001/api/users

### 

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test",
    "name": "test",
    "password": "test"
}

### 

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test23",
    "name": "test",
    "password": "te"
}